
let Assert = NUnit.Assert;


function MyFunc(a, b, c) => (a && b) || c;
function Test_FunctionInvoke()
{
	Assert.IsTrue(MyFunc.Invoke([true, true, false]), "Function.Invoke Failed");
	Assert.IsFalse(MyFunc.Invoke([true, false, false]), "Function.Invoke Failed");
	Assert.IsTrue(MyFunc.Invoke([true, false, true]), "Function.Invoke Failed");

}

NUnit.AddTest(Test_FunctionInvoke, "Function.Invoke tests");