let Assert = NUnit.Assert;

function Test_Interface_MultipleChainTyped()
{
	interface IA<T>
	{
		T F();
	}
	interface IB<T> : IA<T>
	{
		T G();
	}
	class C : IB<bool>
	{
		function bool F()
		{
			return true;
		}

		function bool G()
		{
			return F();
		}
	}

	const IA<bool> i = new C();
	const f = i.F();
	const g = i.G();
	Assert.IsTrue(f && g, "Interface Function did not return true");
}

NUnit.AddTest(Test_Interface_MultipleChainTyped, "Generic Interface Multiple Chain Typed");


