language: csharp
mono: none
sudo: required
dist: xenial

matrix:
  include:
    - dotnet: 6.0
      env:
        - SOLUTION="src/BadScript2.sln"
        - BUILDCONFIG="Release"

install:
  #Restore Projects
  - dotnet restore src/

script:
  - dotnet build $SOLUTION -c $BUILDCONFIG

after_script:
  - dotnet test $SOLUTION --collect:"XPlat Code Coverage" -c $BUILDCONFIG
  #- bash <(curl -s https://codecov.io/bash) #Uploading the coverage report to Codecov.
  - cp $(find . -name "coverage.cobertura.xml") ./cobertura.xml # Copy Report so Codacy picks it up
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) #Uploading the coverage report to Codacy.