
function PrintFiles(dir)
{

	foreach(file in OS.FileSystem.Directory.GetDirectories(dir, false))
	{
		OS.WriteLine("\t- " + file);
	}
	
	foreach(file in OS.FileSystem.Directory.GetFiles(dir, "", false))
	{
		OS.WriteLine("\t- " + file);
	}
	
}


const args = OS.GetArguments();
if(args.Length == 1)
{
	PrintFiles(OS.FileSystem.Directory.GetCurrentDirectory());
}
else if(args.Length == 2)
{
	PrintFiles(args[1]);
}
else
{
	OS.WriteLine("Invalid Argument Count");
}