
let Assert = NUnit.Assert;

function F(x!, y?, args*)
{
	Assert.AreEqual(args.Length, 2, "args.Length == 2");
	Assert.AreEqual(x, true, "x == true");
	Assert.AreEqual(y, 1, "y == 1");
}

function G(x!?)
{
	
}

function Test_FunctionArguments()
{
	F(true, 1, "2", null);
	G();
	G(true);
}

NUnit.AddTest(Test_FunctionArguments, "Mixed Function Argument Tests");

const f = (x!, y?, args*) => Assert.IsTrue(x == true && y == 1 && args.Length == 2, $"Lambda Mixed Argument Error");
function Test_LambdaMixedArgList()
{
	f(true, 1, "2", null);
}

NUnit.AddTest(Test_LambdaMixedArgList, "Mixed Lambda Function Argument List Tests");