
let Assert = NUnit.Assert;


function Test_LogicOr()
{
	Assert.IsTrue(true || true, "true || true");
	Assert.IsTrue(false || true, "false || true");
	Assert.IsTrue(true || false, "true || false");
	Assert.IsFalse(false || false, "false || false");
}

NUnit.AddTest(Test_LogicOr, "Operator '||' tests");


function Test_LogicOrShortCircuit()
{
	const value = null;
	Assert.IsTrue(value == null || value.SomeProperty == 10, "Short-circuit evaluation should prevent null reference");
}

NUnit.AddTest(Test_LogicOrShortCircuit, "Operator '||' short-circuit evaluation tests");