
const _list = [];
function AddToList(context)
{
	foreach(value in context.Request.Query["value"])
	{
		_list.Add(value);
	}
	return {Message: "Success!"}
}

function RemoveFromList(context)
{
	foreach(i in context.Request.Query["index"])
	{
		let index = Runtime.Native.ParseNumber(i);
		_list.RemoveAt(index);
	}
	return {Message: "Success!"}
}

function List(context)
{
	return _list;
}


App.MapGet("/", List);
App.MapGet("/add", AddToList);
App.MapGet("/remove", RemoveFromList);