
let Assert = NUnit.Assert;

function F(x?) {}
function G(x, y?) {}
function H(x?, y?) {}

function Test_OptionalArguments()
{
	F();
	F(true);
	G(true);
	G(true, true);
	H();
	H(true);
	H(true, true);
}

NUnit.AddTest(Test_OptionalArguments, "Optional Function Argument Tests");

function Test_LambdaOptionalArg()
{
	const f = arg? => arg;
	f(true);
	f();
}

NUnit.AddTest(Test_LambdaOptionalArg, "Optional Lambda Function Argument Tests");

function Test_LambdaOptionalArgList()
{
	const f = (arg?) => arg;
	f(true);
	f();
}

NUnit.AddTest(Test_LambdaOptionalArgList, "Optional Lambda Function Argument List Tests");