
let Assert = NUnit.Assert;

function F(x!) {}
function G(x, y!) {}
function H(x!, y!) {}

function Test_NullCheckedArguments()
{
	F(true);
	G(true, true);
	H(true, true);
}

NUnit.AddTest(Test_NullCheckedArguments, "NullChecked Function Argument Tests");

function Test_LambdaNullCheckedArg()
{
	const f = arg! => Assert.IsNotNull(arg, "Arg is null");
	f(true);
}

NUnit.AddTest(Test_LambdaNullCheckedArg, "NullChecked Lambda Function Argument Tests");

function Test_LambdaNullCheckedArgList()
{
	const f = (arg!) => Assert.IsNotNull(arg, "Arg is null");
	f(true);
}

NUnit.AddTest(Test_LambdaNullCheckedArgList, "NullChecked Lambda Function Argument List Tests");