
let Assert = NUnit.Assert;

function F(args*)
{
	Assert.AreEqual(args.Length, 4, "args.Length == 4");	
}

function Test_RestArgs()
{
	F(true, 1, "2", null);
}

NUnit.AddTest(Test_RestArgs, "Rest Function Argument Tests");


function Test_LambdaRestArgs()
{
	const f = args* => Assert.AreEqual(args.Length, 4, "args.Length == 4");
	f(true, 1, "2", null);
}

NUnit.AddTest(Test_LambdaRestArgs, "Rest Lambda Function Argument Tests");

function Test_LambdaRestArgList()
{
	const f = (args*) => Assert.AreEqual(args.Length, 4, "args.Length == 4");
	f(true, 1, "2", null);
}

NUnit.AddTest(Test_LambdaRestArgList, "Rest Lambda Function Argument List Tests");