
let Assert = NUnit.Assert;


function Test_ArrayAccess()
{
	let a = [1, 2, 3];
	Assert.AreEqual(a[2], 3, "a[2] == 3");

	a = { A: 2 };
	Assert.AreEqual(a["A"], 2, "a[\"A\"] == 2");
}

NUnit.AddTest(Test_ArrayAccess, "Operator '[]' tests");


function Test_EnumeratedArrayAccess()
{
	let a = ["ABC", "Hallo", "Welt"];
	let aResult = a[1..a.Length];
	Assert.AreEqual(aResult[0], "Hallo", "aResult[0] == \"Hallo\"");
	Assert.AreEqual(aResult[1], "Welt", "aResult[1] == \"Welt\"");

	a = { A: 2, B: 3, C: 4 };
	aResult = a[["A", "C"]];
	Assert.AreEqual(aResult["A"], 2, "aResult[\"A\"] == 2");
	Assert.IsFalse("B" in aResult, "\"B\" in aResult");
	Assert.AreEqual(aResult["C"], 4, "aResult[\"C\"] == 4");
}

NUnit.AddTest(Test_EnumeratedArrayAccess, "Enumerated Operator '[]' tests");