let Assert = NUnit.Assert;

function Test_Interface_MultipleChainTyped()
{
	interface IA
	{
		bool F();
	}
	interface IB : IA
	{
		bool G();
	}
	class C : IB
	{
		function bool F()
		{
			return true;
		}

		function bool G()
		{
			return F();
		}
	}

	const IA i = new C();
	const f = i.F();
	const g = i.G();
	Assert.IsTrue(f && g, "Interface Function did not return true");
}

NUnit.AddTest(Test_Interface_MultipleChainTyped, "Interface Multiple Chain Typed");


