
function GetRelative(string file!)
{
	return IO.Path.Combine(IO.Path.GetDirectoryName(BadHtml.TemplateFile), file);
}

function Load(string file!)
{
	return IO.File.ReadAllText(GetRelative(file));
}


function LoadJson(string file!)
{
	return Json.FromJson(Load(file));
}

function LoadTemplate(string file!, model?)
{
	return BadHtml.FromFile(GetRelative(file), model);
}


return {
	GetRelative: GetRelative,
	Load: Load,
	LoadJson: LoadJson,
	LoadTemplate: LoadTemplate
}