
let Assert = NUnit.Assert;


function Test_Equal()
{
	Assert.IsFalse(true == false, "true == false");
	Assert.IsFalse(1 == 2, "1 == 2");
	Assert.IsFalse("B" == "A", "\"B\" == \"A\"");
	Assert.IsFalse(1 == 0.9999, "1 == 0.9999");
	Assert.IsFalse({} == {}, "{} == {}");
	Assert.IsFalse([] == [], "[] == []");
	Assert.IsFalse(1 == true, "1 == true");
	Assert.IsFalse(null == false, "null == false");
	Assert.IsFalse(true == null, "true == null");
}

NUnit.AddTest(Test_Equal, "Operator '==' tests");