import CommandlineParser from './Main.bs';



function ParseArgs()
{
	const parser = new CommandlineParser(false);
	parser.Flag("debug", "d", "Enables Debug Mode")
		.Flag("no-output", "no", "Disables the Console Output")
		.Value("file", "f", true, "The File Name(s) to Load", true)
		.Value("debugger", "dp", false, "The (optional) path to the debugger file", false);
	const args = Runtime.GetArguments();
	const result;
	try
	{
		result = parser.Parse(args);
	}
	catch(e)
	{
		Console.WriteLine(parser.GetHelpText());
		throw e;
	}

	return result;
}
const args = ParseArgs();

function Log(msg)
{
	if(!args.HasFlag("no-output"))
	{
		Console.WriteLine(msg);
	}
}

function Main()
{
	if(args.HasFlag("debug"))
	{
		let debugger = "<default debugger path>";
		if(args.HasValue("debugger"))
		{
			debugger = args.GetValue("debugger");
		}
		Log($"Debugging with {debugger}");
	}

	const file = args.GetValue("file");
	Log("Using File: " + file);
	foreach(n in 0..10)
	{
		Log("Iteration " + n);
	}
}


Main();
